/name=NeuralEngine
version=1.0.0
author=Skynetbee IoT Wing
maintainer=Skynet IoT Wing <Skynetiotwing@gmail.com>
sentence=Skynetbee ToT Wing.
paragraph=Skynetbee ToT Wing.
category=IoT
url=https://github.com/yourusername/NeuralEngine
architectures=esp32
includes=NeuralEngine.h
